services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: school_management_ideal-cms-backend

    restart: unless-stopped

    env_file:
      - ./backend/.env

    ports:
      - "8015:8000"

    networks:
      - ideal-cms-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: school_management_ideal-cms-frontend

    restart: unless-stopped

    depends_on:
      - backend

    environment:
      REACT_APP_BACKEND_URL: http://localhost:8015

    ports:
      - "3015:80"

    networks:
      - ideal-cms-network

networks:
  ideal-cms-network:
    driver: bridge